@startuml
'https://plantuml.com/class-diagram

class CompetenceReview {
    -competenceInputPort: CompetenceInputPort
    -trackScore: ArrayList<Integer>
    -questionList: ArrayList<Question>

    +addQuestions(questions: ArrayList<Question>): void
    +initReview(userInput: String): bool
    +runReview(): void
    +sumScore(list: List<Integer>): int
    +getBestResult(): int
    +calculateResult(userScore: int, maxScore: int, thresholds[]: double): int
    +setUserConfig(currentUser: User, configId: int): void
}

class checkUIConfig {
    -competenceInputPort: CompetenceInputPort

    +checkConfig(currentUser: User): bool

}

class Question {
    -questionType: String
    -questionDescription: String
    -choices: Map<String, Integer>
}

class User {
    -userId: String
    -configId: int
}

CompetenceReview o-- Question
@enduml
