@startuml
'https://plantuml.com/class-diagram

class CompetenceTest {
    #configID: int
    #currentUser: UserDummy
    #trackResult: List<Integer>
    #questions: ArrayList<Question>

    +checkConfig(): int
    +runTest(): void
    +calculateResult(): int
    +singleChoice(): int
    +rangeChoice(): int

}

class Question {
    #question: string
    #textAnswers: HashMap<String, Integer>
    #numAnswers: HashMap<Integer, Integer>
}

class UserDummy {
    #userID: string
    #configID: int
}

CompetenceTest o-- Question
CompetenceTest o-- UserDummy
@enduml
